#!/bin/sh
CPATH=`pwd`
WBIN=../chaos_bin/devel/windows
LBIN=../chaos_bin/devel/linux

# Linux
echo ##################
echo " LINUX BUILD "
echo ##################
rm -rf debug release
make clean
make build_release -j
cd release
bzip2 gamex86_64.so
cd ..
mv -vf release/gamex86_64.so.bz2 ${LBIN}/

# windows x86
echo ##################
echo " WIN32 BUILD "
echo ##################
cp -vf .config32 .config
make -f Makefile_mingw clean
make -f Makefile_mingw -j
bzip2 gamex86.dll
mv -vf gamex86.dll.bz2 ${WBIN}/

# windows x86_64
echo ##################
echo " WIN64 BUILD "
echo ##################
cp -vf .config64 .config
make -f Makefile_mingw clean
make -f Makefile_mingw -j
bzip2 gamex86_64.dll
mv -vf gamex86_64.dll.bz2 ${WBIN}/
