#!/bin/sh
# antoine@ginies.org
# simple script to build chaos for linux, win32 and win64
CPATH=`pwd`
WBIN=../chaos_bin/devel/windows
LBIN=../chaos_bin/devel/linux

# Linux
linux() {
echo ##################
echo " linux build "
echo ##################
rm -rf release
make clean
make build_release -j
cp -vf release/gamex86_64.so ~/quake2/chaos/
cd release
bzip2 gamex86_64.so
cd ..
mv -vf release/gamex86_64.so.bz2 ${LBIN}/
}

linuxd() {
echo ##################
echo " linux debug build "
echo ##################
rm -rf debug
make clean
make build_debug -j
cp -vf debug/gamex86_64.so ~/quake2/chaos/
}

## windows x86
windows32() {
echo ##################
echo " WIN32 BUILD "
echo ##################
cp -vf .config32 .config
make -f Makefile_mingw clean
make -f Makefile_mingw -j
bzip2 gamex86.dll
cp -vf gamex86.dll.bz2 ${WBIN}/
}

window64() {
# windows x86_64
echo ##################
echo " WIN64 BUILD "
echo ##################
cp -vf .config64 .config
make -f Makefile_mingw clean
make -f Makefile_mingw -j
bzip2 gamex86_64.dll
cp -vf gamex86_64.dll.bz2 ${WBIN}/
}

linuxd
linux
windows32
window64
